# Generated by Django 5.1.6 on 2025-03-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_event_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerparticipation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='volunteers.volunteerpositions'),
        ),
    ]
