# Generated by Django 5.1.6 on 2025-03-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_volunteerparticipation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerparticipation',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteers.volunteer'),
        ),
    ]
