# Generated by Django 5.1.6 on 2025-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_alter_volunteerparticipation_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerparticipation',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Declined', 'declined'), ('Approved', 'approved')], default='pending', max_length=10),
        ),
    ]
