# Generated by Django 5.1.6 on 2025-03-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_alter_volunteerparticipation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='responsible',
        ),
        migrations.AddField(
            model_name='volunteerparticipation',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
