# Generated by Django 5.1.6 on 2025-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_remove_locations_responsible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтер', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AlterModelOptions(
            name='volunteerparticipation',
            options={'verbose_name': 'Заявка волонтера', 'verbose_name_plural': 'Заявки волонтеров'},
        ),
        migrations.AlterModelOptions(
            name='volunteerpositions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='volunteerparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
